version: '2'
services:
    eibhackathon-app:
        image: eibhackathon
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://eibhackathon-mysql:3306/eibhackathon?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    eibhackathon-mysql:
        extends:
            file: mysql.yml
            service: eibhackathon-mysql
